networks:
  default:
    name: j2ee-network

volumes:
  j2ee-m2-volume:

services:
  maven-build:
    image: maven:3.9.0-eclipse-temurin-17
    volumes:
      - .:/usr/src/build
      - j2ee-m2-volume:/root/.m2
    working_dir: /usr/src/build
    command: mvn clean install

  db-mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: j2eedemo
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - j2eedemo-mysql

  web:
    container_name: web
    build:
      context: web
      args:
        version: ${VERSION}
        hikaricp_URL: ${HIKARICP_URL}
        sfl4j_api_URL: ${SFL4J_API_URL}
        mysql_connector_j_URL: ${MYSQL_CONNECTOR_J_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/local/tomcat/logs